modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="fluidcows"
version="1.0.3"
displayName="FluidCows(REBORN)"
description='''Cows that produce registered fluids instead of milk.'''

[[dependencies.fluidcows]]
modId="neoforge"
mandatory=true
versionRange="[21.1.0,)"
